### PR TITLE
[Networks] Add Megacoin Support

### PR DESCRIPTION
**Pull request by dalijolijo**
Source code: https://github.com/LIMXTEC/Megacoin

### CODE REVIEW

**Comment by ahmedbodi** [comment]
If you'd like, you can make similar changes to electrum-altcoin/electrum to create an easy electrum wallet

**Comment by dalijolijo** [comment]
> If you'd like, you can make similar changes to electrum-altcoin/electrum to create an easy electrum wallet
Yes, I am interested. What do I have to consider for the electrum client implementation?

**Comment by ahmedbodi** [comment]
It's mostly the same as this PR, You can use this as a template https://github.com/electrum-altcoin/electrum/pull/32

**Comment by dalijolijo** [comment]
Can I also use this PR https://github.com/electrum-altcoin/electrum/pull/31 as a template?

**Comment by ahmedbodi** [comment]
yep sure

**Pull request merged**
